name: Tenbatsu
version: ${project.version}
main: dev.notmarra.tenbatsu.Tenbatsu
api-version: '1.21'
authors: [ NotMarra ]
description: Minecraft ban system
website: wiki.notmarra.dev
dependencies:
  server:
    NotLib:
      load: BEFORE
      required: true